### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/midcat#1]
* [x] port what I've done in https://github.com/moul/music-paint
* [x] midi client/server
* [x] ctrl+c handling with context
* [x] as a library
* [ ] write doc about how to use it in various cases in the README
* [ ] show examples of piping
* [ ] socket.io server
* [ ] socket.io client
* [ ] midi filter
* [ ] .mid file parsing/generation
* [ ] hardware listing
* [ ] ticker
* [ ] HTTP client
* [ ] raw-text/json (pipe)
* [ ] web chrome API
* [ ] bluetooth API
* [ ] unit tests
* [ ] filters
* [ ] support portmidi and other drivers
